# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SIM.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SIM.proto',
  package='teensy._3_1.sim',
  serialized_pb=_b('\n\tSIM.proto\x12\x0fteensy._3_1.sim\"\xd0\x01\n\x07R_SCGC6\x12\x0b\n\x03RTC\x18\x01 \x01(\x08\x12\x0c\n\x04\x41\x44\x43\x30\x18\x02 \x01(\x08\x12\x0c\n\x04\x46TM1\x18\x03 \x01(\x08\x12\x0c\n\x04\x46TM0\x18\x04 \x01(\x08\x12\x0b\n\x03PIT\x18\x05 \x01(\x08\x12\x0b\n\x03PDB\x18\x06 \x01(\x08\x12\x0e\n\x06USBDCD\x18\x07 \x01(\x08\x12\x0b\n\x03\x43RC\x18\x08 \x01(\x08\x12\x0b\n\x03I2S\x18\t \x01(\x08\x12\x0c\n\x04SPI1\x18\n \x01(\x08\x12\x0c\n\x04SPI0\x18\x0b \x01(\x08\x12\x10\n\x08\x46LEXCAN0\x18\x0c \x01(\x08\x12\x0e\n\x06\x44MAMUX\x18\r \x01(\x08\x12\x0c\n\x04\x46TFL\x18\x0e \x01(\x08\"\x16\n\x07R_SCGC7\x12\x0b\n\x03\x44MA\x18\x01 \x01(\x08\"\x8d\x03\n\tRegisters\x12\r\n\x05SOPT1\x18\x01 \x01(\r\x12\x10\n\x08SOPT1CFG\x18\x02 \x01(\r\x12\r\n\x05SOPT2\x18\x03 \x01(\r\x12\r\n\x05SOPT4\x18\x04 \x01(\r\x12\r\n\x05SOPT5\x18\x05 \x01(\r\x12\r\n\x05SOPT7\x18\x06 \x01(\r\x12\x0c\n\x04SDID\x18\x07 \x01(\r\x12\r\n\x05SCGC1\x18\x08 \x01(\r\x12\r\n\x05SCGC2\x18\t \x01(\r\x12\r\n\x05SCGC3\x18\n \x01(\r\x12\r\n\x05SCGC4\x18\x0b \x01(\r\x12\r\n\x05SCGC5\x18\x0c \x01(\r\x12\'\n\x05SCGC6\x18\r \x01(\x0b\x32\x18.teensy._3_1.sim.R_SCGC6\x12\'\n\x05SCGC7\x18\x0e \x01(\x0b\x32\x18.teensy._3_1.sim.R_SCGC7\x12\x0f\n\x07\x43LKDIV1\x18\x0f \x01(\r\x12\x0f\n\x07\x43LKDIV2\x18\x10 \x01(\r\x12\r\n\x05\x46\x43\x46G1\x18\x11 \x01(\r\x12\r\n\x05\x46\x43\x46G2\x18\x12 \x01(\r\x12\x0c\n\x04UIDH\x18\x13 \x01(\r\x12\r\n\x05UIDMH\x18\x14 \x01(\r\x12\r\n\x05UIDML\x18\x15 \x01(\r\x12\x0c\n\x04UIDL\x18\x16 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_R_SCGC6 = _descriptor.Descriptor(
  name='R_SCGC6',
  full_name='teensy._3_1.sim.R_SCGC6',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RTC', full_name='teensy._3_1.sim.R_SCGC6.RTC', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ADC0', full_name='teensy._3_1.sim.R_SCGC6.ADC0', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FTM1', full_name='teensy._3_1.sim.R_SCGC6.FTM1', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FTM0', full_name='teensy._3_1.sim.R_SCGC6.FTM0', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PIT', full_name='teensy._3_1.sim.R_SCGC6.PIT', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PDB', full_name='teensy._3_1.sim.R_SCGC6.PDB', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='USBDCD', full_name='teensy._3_1.sim.R_SCGC6.USBDCD', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CRC', full_name='teensy._3_1.sim.R_SCGC6.CRC', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='I2S', full_name='teensy._3_1.sim.R_SCGC6.I2S', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SPI1', full_name='teensy._3_1.sim.R_SCGC6.SPI1', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SPI0', full_name='teensy._3_1.sim.R_SCGC6.SPI0', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FLEXCAN0', full_name='teensy._3_1.sim.R_SCGC6.FLEXCAN0', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DMAMUX', full_name='teensy._3_1.sim.R_SCGC6.DMAMUX', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FTFL', full_name='teensy._3_1.sim.R_SCGC6.FTFL', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=239,
)


_R_SCGC7 = _descriptor.Descriptor(
  name='R_SCGC7',
  full_name='teensy._3_1.sim.R_SCGC7',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DMA', full_name='teensy._3_1.sim.R_SCGC7.DMA', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=263,
)


_REGISTERS = _descriptor.Descriptor(
  name='Registers',
  full_name='teensy._3_1.sim.Registers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SOPT1', full_name='teensy._3_1.sim.Registers.SOPT1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SOPT1CFG', full_name='teensy._3_1.sim.Registers.SOPT1CFG', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SOPT2', full_name='teensy._3_1.sim.Registers.SOPT2', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SOPT4', full_name='teensy._3_1.sim.Registers.SOPT4', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SOPT5', full_name='teensy._3_1.sim.Registers.SOPT5', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SOPT7', full_name='teensy._3_1.sim.Registers.SOPT7', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SDID', full_name='teensy._3_1.sim.Registers.SDID', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SCGC1', full_name='teensy._3_1.sim.Registers.SCGC1', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SCGC2', full_name='teensy._3_1.sim.Registers.SCGC2', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SCGC3', full_name='teensy._3_1.sim.Registers.SCGC3', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SCGC4', full_name='teensy._3_1.sim.Registers.SCGC4', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SCGC5', full_name='teensy._3_1.sim.Registers.SCGC5', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SCGC6', full_name='teensy._3_1.sim.Registers.SCGC6', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SCGC7', full_name='teensy._3_1.sim.Registers.SCGC7', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CLKDIV1', full_name='teensy._3_1.sim.Registers.CLKDIV1', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CLKDIV2', full_name='teensy._3_1.sim.Registers.CLKDIV2', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FCFG1', full_name='teensy._3_1.sim.Registers.FCFG1', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FCFG2', full_name='teensy._3_1.sim.Registers.FCFG2', index=17,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UIDH', full_name='teensy._3_1.sim.Registers.UIDH', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UIDMH', full_name='teensy._3_1.sim.Registers.UIDMH', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UIDML', full_name='teensy._3_1.sim.Registers.UIDML', index=20,
      number=21, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UIDL', full_name='teensy._3_1.sim.Registers.UIDL', index=21,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=663,
)

_REGISTERS.fields_by_name['SCGC6'].message_type = _R_SCGC6
_REGISTERS.fields_by_name['SCGC7'].message_type = _R_SCGC7
DESCRIPTOR.message_types_by_name['R_SCGC6'] = _R_SCGC6
DESCRIPTOR.message_types_by_name['R_SCGC7'] = _R_SCGC7
DESCRIPTOR.message_types_by_name['Registers'] = _REGISTERS

R_SCGC6 = _reflection.GeneratedProtocolMessageType('R_SCGC6', (_message.Message,), dict(
  DESCRIPTOR = _R_SCGC6,
  __module__ = 'SIM_pb2'
  # @@protoc_insertion_point(class_scope:teensy._3_1.sim.R_SCGC6)
  ))
_sym_db.RegisterMessage(R_SCGC6)

R_SCGC7 = _reflection.GeneratedProtocolMessageType('R_SCGC7', (_message.Message,), dict(
  DESCRIPTOR = _R_SCGC7,
  __module__ = 'SIM_pb2'
  # @@protoc_insertion_point(class_scope:teensy._3_1.sim.R_SCGC7)
  ))
_sym_db.RegisterMessage(R_SCGC7)

Registers = _reflection.GeneratedProtocolMessageType('Registers', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERS,
  __module__ = 'SIM_pb2'
  # @@protoc_insertion_point(class_scope:teensy._3_1.sim.Registers)
  ))
_sym_db.RegisterMessage(Registers)


# @@protoc_insertion_point(module_scope)
