
/* #########################################################################
 * [2017-09-15 16:55:24.964000] THIS FILE IS AUTOGENERATED - DO NOT EDIT!
 * ######################################################################### */

#ifndef ___TEENSY_MINIMAL_RPC___
#define ___TEENSY_MINIMAL_RPC___

#include "TeensyMinimalRpc/Properties.h"
#include "TeensyMinimalRpc/CommandProcessor.h"

#endif  // #ifndef ___TEENSY_MINIMAL_RPC___

